// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MailAccountService manages email accounts
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddAccount adds a new account
 */
export function AddAccount(account: $models.Account | null): $CancellablePromise<$models.Account | null> {
    return $Call.ByID(3570805671, account).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteAccount deletes an account
 */
export function DeleteAccount(id: string): $CancellablePromise<void> {
    return $Call.ByID(2548784873, id);
}

/**
 * GetAccount returns an account by ID
 */
export function GetAccount(id: string): $CancellablePromise<$models.Account | null> {
    return $Call.ByID(2481708182, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetAccounts returns all accounts
 */
export function GetAccounts(): $CancellablePromise<($models.Account | null)[]> {
    return $Call.ByID(3243031679).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * UpdateAccount updates an existing account
 */
export function UpdateAccount(account: $models.Account | null): $CancellablePromise<void> {
    return $Call.ByID(975806943, account);
}

// Private type creation functions
const $$createType0 = $models.Account.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
