// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MailService handles email operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetEmail retrieves a specific email with body, with cache support
 */
export function GetEmail(accountID: string, folder: string, uid: number): $CancellablePromise<$models.Email | null> {
    return $Call.ByID(55669524, accountID, folder, uid).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetEmails retrieves emails from a folder with cache support
 * forceRefresh: if true, bypass cache and fetch from server
 */
export function GetEmails(accountID: string, folder: string, page: number, pageSize: number, forceRefresh: boolean): $CancellablePromise<($models.Email | null)[]> {
    return $Call.ByID(2688068389, accountID, folder, page, pageSize, forceRefresh).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SendEmail(req: $models.SendEmailRequest | null): $CancellablePromise<void> {
    return $Call.ByID(1988209338, req);
}

/**
 * TestConnection tests if an account's connection works
 */
export function TestConnection(accountID: string): $CancellablePromise<void> {
    return $Call.ByID(1501221972, accountID);
}

// Private type creation functions
const $$createType0 = $models.Email.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
