// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Account represents an email account configuration
 */
export class Account {
    "id": string;
    "name": string;
    "email": string;
    "imapHost": string;
    "imapPort": number;
    "imapUseSSL": boolean;
    "smtpHost": string;
    "smtpPort": number;
    "smtpUseSSL": boolean;

    /**
     * Use SMTP or IMAP
     */
    "emailProtocolUse": string;
    "username": string;

    /**
     * In production, this should be encrypted
     */
    "password": string;
    "createdAt": string;

    /** Creates a new Account instance. */
    constructor($$source: Partial<Account> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("email" in $$source)) {
            this["email"] = "";
        }
        if (!("imapHost" in $$source)) {
            this["imapHost"] = "";
        }
        if (!("imapPort" in $$source)) {
            this["imapPort"] = 0;
        }
        if (!("imapUseSSL" in $$source)) {
            this["imapUseSSL"] = false;
        }
        if (!("smtpHost" in $$source)) {
            this["smtpHost"] = "";
        }
        if (!("smtpPort" in $$source)) {
            this["smtpPort"] = 0;
        }
        if (!("smtpUseSSL" in $$source)) {
            this["smtpUseSSL"] = false;
        }
        if (!("emailProtocolUse" in $$source)) {
            this["emailProtocolUse"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Account instance from a string or object.
     */
    static createFrom($$source: any = {}): Account {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Account($$parsedSource as Partial<Account>);
    }
}

/**
 * Email represents an email message
 */
export class Email {
    "id": string;
    "accountId": string;
    "folder": string;
    "uid": number;
    "from": string;
    "to": string[];
    "cc": string[];
    "subject": string;
    "date": string;
    "body": string;
    "isRead": boolean;
    "isStarred": boolean;
    "createdAt": string;

    /** Creates a new Email instance. */
    constructor($$source: Partial<Email> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("accountId" in $$source)) {
            this["accountId"] = "";
        }
        if (!("folder" in $$source)) {
            this["folder"] = "";
        }
        if (!("uid" in $$source)) {
            this["uid"] = 0;
        }
        if (!("from" in $$source)) {
            this["from"] = "";
        }
        if (!("to" in $$source)) {
            this["to"] = [];
        }
        if (!("cc" in $$source)) {
            this["cc"] = [];
        }
        if (!("subject" in $$source)) {
            this["subject"] = "";
        }
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("isRead" in $$source)) {
            this["isRead"] = false;
        }
        if (!("isStarred" in $$source)) {
            this["isStarred"] = false;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Email instance from a string or object.
     */
    static createFrom($$source: any = {}): Email {
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("to" in $$parsedSource) {
            $$parsedSource["to"] = $$createField5_0($$parsedSource["to"]);
        }
        if ("cc" in $$parsedSource) {
            $$parsedSource["cc"] = $$createField6_0($$parsedSource["cc"]);
        }
        return new Email($$parsedSource as Partial<Email>);
    }
}

/**
 * Folder represents a mailbox folder
 */
export class Folder {
    "name": string;
    "unread": number;
    "total": number;

    /** Creates a new Folder instance. */
    constructor($$source: Partial<Folder> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("unread" in $$source)) {
            this["unread"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Folder instance from a string or object.
     */
    static createFrom($$source: any = {}): Folder {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Folder($$parsedSource as Partial<Folder>);
    }
}

/**
 * SendEmail sends an email
 */
export class SendEmailRequest {
    "accountId": string;
    "to": string[];
    "cc": string[];
    "bcc": string[];
    "subject": string;
    "body": string;
    "isHTML": boolean;

    /** Creates a new SendEmailRequest instance. */
    constructor($$source: Partial<SendEmailRequest> = {}) {
        if (!("accountId" in $$source)) {
            this["accountId"] = "";
        }
        if (!("to" in $$source)) {
            this["to"] = [];
        }
        if (!("cc" in $$source)) {
            this["cc"] = [];
        }
        if (!("bcc" in $$source)) {
            this["bcc"] = [];
        }
        if (!("subject" in $$source)) {
            this["subject"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("isHTML" in $$source)) {
            this["isHTML"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SendEmailRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SendEmailRequest {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("to" in $$parsedSource) {
            $$parsedSource["to"] = $$createField1_0($$parsedSource["to"]);
        }
        if ("cc" in $$parsedSource) {
            $$parsedSource["cc"] = $$createField2_0($$parsedSource["cc"]);
        }
        if ("bcc" in $$parsedSource) {
            $$parsedSource["bcc"] = $$createField3_0($$parsedSource["bcc"]);
        }
        return new SendEmailRequest($$parsedSource as Partial<SendEmailRequest>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
