// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NoteService manages notes and folders
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateFolder creates a new note folder
 */
export function CreateFolder(name: string): $CancellablePromise<void> {
    return $Call.ByID(778040411, name);
}

/**
 * DeleteFolder deletes a note folder and all its notes
 */
export function DeleteFolder(name: string): $CancellablePromise<void> {
    return $Call.ByID(1464531392, name);
}

/**
 * DeleteNote deletes a note
 */
export function DeleteNote(folder: string, noteID: string): $CancellablePromise<void> {
    return $Call.ByID(2859584032, folder, noteID);
}

/**
 * GetConfig returns the current configuration
 */
export function GetConfig(): $CancellablePromise<$models.NoteConfig> {
    return $Call.ByID(3868022035).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetFolders returns all note folders
 */
export function GetFolders(): $CancellablePromise<$models.NoteFolder[]> {
    return $Call.ByID(2909666214).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetNote returns a specific note by ID
 */
export function GetNote(folder: string, noteID: string): $CancellablePromise<$models.Note | null> {
    return $Call.ByID(294022025, folder, noteID).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetNotes returns all notes in a folder
 */
export function GetNotes(folder: string): $CancellablePromise<$models.Note[]> {
    return $Call.ByID(2426141326, folder).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * SaveNote saves or updates a note
 */
export function SaveNote(folder: string, note: $models.Note): $CancellablePromise<void> {
    return $Call.ByID(2870063358, folder, note);
}

/**
 * SetDefaultDir sets the default directory for notes
 */
export function SetDefaultDir(dir: string): $CancellablePromise<void> {
    return $Call.ByID(2807665517, dir);
}

// Private type creation functions
const $$createType0 = $models.NoteConfig.createFrom;
const $$createType1 = $models.NoteFolder.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.Note.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType3);
